<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
 
    <groupId>ubc.cosc322</groupId>
    <artifactId>team-00</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
     

    <name>COSC322-Team-00</name>
    <description>COSC 322 Game Player Project</description>
    <inceptionYear>2021</inceptionYear>
    
	
    <dependencies> 
        <dependency>	        
	    <groupId>ubc-yong-gao</groupId>
            <artifactId>ygraph-ai-smartfox-client</artifactId>
            <version>2.1</version>
            <type>jar</type>
        </dependency>
    
      <dependency>
        <groupId>org.apache.ant</groupId>
        <artifactId>ant</artifactId>
        <version>1.10.15</version>
      </dependency>
    </dependencies>
	
    <repositories>
        <repository>
            <id>ubc-yong-gao</id>
            <name>ubc-yong-gao</name>
            <url>https://cmps-people.ok.ubc.ca/yongg/computing_resources/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
    
    <url>https:people.ok.uc.ca/yongg</url>
    <developers>
        <developer>
            <id>Team-00</id>
            <name>Team members</name>
            <email></email>
        </developer> 
        <developer>
            <id>yg</id>
            <name>Yong Gao</name>
            <email>yong.gao@ubc.ca</email>
        </developer> 
    </developers>

    <build>
    <plugins>
        <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>3.6.0</version>
        <configuration>
            <archive>
            <manifest>
                <mainClass>ubc.cosc322.COSC322Test</mainClass>
            </manifest>
            </archive>
            <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
            </descriptorRefs>
        </configuration>
        <executions>
            <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals><goal>single</goal></goals>
            </execution>
        </executions>
        </plugin>
    </plugins>
    </build>
    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
</project>
